[package]
name = "dict"
version = "0.1.0"
authors = ["ede1998 <online@erik-hennig.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.10.1"
reqwest = "0.9.19"
itertools = "0.8.0"

[dev-dependencies]
lazy_static = "1.3.0"
