[package]
name = "dict"
version = "1.4.4"
authors = ["ede1998 <online@erik-hennig.me>"]
edition = "2018"
description = "A small command-line translator. It queries the dict.cc website for translations."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.12"
reqwest = { version = "0.11", features= ["blocking"] }
itertools = "0.10"
clap = "2.33"
url = "2.2.2"
